### ISSUE TITLE
Please release 1.1.3

### ISSUE THREAD

**Issue by oldenboom** [jmfederico/django-use-email-as-username#10]
* Django use Email as Username version: 1.1.2
* Django version: 4.0
* Python version: 3.9.9
* Operating System: macOS

### Description

Trying to migrate my project to Django 4.0. This release drops support fur ugettext. While upgrading my virtual environment using pip, 1.1.2 of django-use-email-as-username got installed again even though you did fix this ugettext issue already.

Please tag the current version.

**Comment by jmfederico** [comment]
Version [1.2.0](https://github.com/jmfederico/django-use-email-as-username/releases/tag/v1.2.0) released
