### ISSUE TITLE
Following readme, Create your new django app throws error

### ISSUE THREAD

**Issue by gjohnrao** [jmfederico/django-use-email-as-username#11]
* Django use Email as Username version: latest
* Django version: lastest
* Python version: 3.9
* Operating System: Windoes

From readme steps:

3. Create your new django app:

```
python manage.py create_custom_user_app

Error: TypeError: requires_system_checks must be a list or tuple.


```

**Comment by benoitperrin** [comment]
Hi @johnrao7,

Same here.

This seems to be an incompatibility with Django 4.1, documented in [Django #31546]( https://code.djangoproject.com/ticket/31546). Our library shows an error when [this line of code](https://github.com/jmfederico/django-use-email-as-username/blob/main/django_use_email_as_username/management/commands/create_custom_user_app.py#L12) is called.

As a workaround, you can downgrade Django to v4.0.8, run the command and upgrade again.

**Comment by jmfederico** [comment]
Fixed in https://github.com/jmfederico/django-use-email-as-username/releases/tag/v1.3.0
