### ISSUE TITLE
Encrypting email that is used as login

### ISSUE THREAD

**Issue by dizzydes** [jmfederico/django-use-email-as-username#13]
* Django use Email as Username version: 1.2.0
* Django version: 3.2.16
* Python version: 3.10
* Operating System: OSX / GAE on Ubuntu

### Description

I'm planning to encrypt an email field that is used for authentication using [django-pgcrypto-fields](https://github.com/incuna/django-pgcrypto-fields). I'd be using symmetric encryption which allows for functions like .get and .filter and returns the plaintext when such functions are used. Would this be enough to ensure custom login with email still works? If not, what other functionality should be required. If not, what other approaches are possible? 

### What I did

Nothing yet, asking ahead for red flags.
Thanks

**Comment by jmfederico** [comment]
The authentication process is handle by Django, this app does not interfere with the auth process itself, it only instructs Django which fields to use for authenticating.

Considering out of scope for this project.
