### ISSUE TITLE
Expanded Readme

### ISSUE THREAD

**Issue by DianaProbst** [jmfederico/django-use-email-as-username#16]
Your README says 'You can further modify the new User Model any time in the future, just remember to create and run the migrations.'

Is it possible to have an example of that?  I'm trying to work out how to modify that user model, as I'd like to be able to give it a class method, but I don't have the context to work out how.

**Comment by jmfederico** [comment]
Please let me know if this link helps https://docs.djangoproject.com/en/dev/topics/auth/customizing/#extending-the-existing-user-model
