### ISSUE TITLE
Add __init__.py so it works with python 2

### ISSUE THREAD

**Issue by a-p-f** [jmfederico/django-use-email-as-username#2]
* Django use Email as Username version:
django-use-email-as-username==1.0.0
* Django version:
Django==1.11.13
* Python version:
Python 2.7.13

The management command doesn't work in python 2 (ImportError: No module named management.commands.create_custom_user_app).

I added __init__.py files in management/ and management/commands/, and now it works fine. Can you add this in? I can submit a pull request if required, but I don't imagine it's necessary for such a small change.

**Comment by jmfederico** [comment]
I have not tested this in Python 2.

If you can create a PR also changing the tox configuration including Python 2 to the tests, I will merge if the tests all pass.

Thanks

**Comment by jmfederico** [comment]
I tried to run the tests against Python 2, but I am using some Python 3 libraries for the tests, which do not allow them to run.

A PR will always be welcomed and appreciated.

**Comment by a-p-f** [comment]
I gave this a brief try, but I'm not terribly familiar with your testing framework and I couldn't get it to work. My work is now moving to python 3 for new projects, so we don't really need this feature anymore. I'm marking as closed. 

Thanks for this useful module.
