### ISSUE TITLE
Custom User model with no username field

### ISSUE THREAD

**Issue by AeroHil** [jmfederico/django-use-email-as-username#3]
Can you make username as an optional field? Would be nice if I can provide the user a "handle" possibly unique as well?

**Comment by jmfederico** [comment]
You can probably not use this module, and just specify `USERNAME_FIELD = "email"` in a custom User model of yours. I have not tested that approach but should work, since that is why Django provides the attribute property.

If you try that please let me know. If it works, we can close this issue. If it does not, I would be open to a PR with this functionality.

**Comment by AeroHil** [comment]
Yes, I was able to do something like this, and redefine both fields
```
EMAIL_FIELD = 'username'
USERNAME_FIELD = 'email'
```

But I really liked the way you wrapped this in a package format so devs don't have to maintain extraneous code. Just wondering if you might possibly add it as an enhancement in the future. Don't worry you haven't got the time.

Thanks

**Comment by AeroHil** [comment]
Here is my custom User class expanding on what you have

```
class User(AbstractUser):
    """User model."""

    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    email = models.EmailField(_('email address'), unique=True)

    EMAIL_FIELD = 'username'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()
```

Also need to make sure the default auth User model isn't being used anymore and replace it with the following in all files going forward
```
from django.contrib.auth import get_user_model
...
User = get_user_model()
```
